### ISSUE TITLE
command for server version

### ISSUE THREAD

**Issue by gregwebs** [TonyGen/mongoDB-haskell#2]
I want to check the server version at startup. This is a broader issue of being able to run a raw command- I would happily parse a string result from the version() command

**Comment by TonyGen** [comment]
Hi Greg,

You can run commands. See http://hackage.haskell.org/packages/archive/mongoDB/1.0.1/doc/html/Database-MongoDB-Query.html#g:15

Cheers,
Tony

**Comment by gregwebs** [comment]
I am probably doing something really stupid. Here is my attempt:

``` haskell
  let js = MongoDB.Javascript [] "version()"
  v <- MongoDB.eval js
  liftIO $ putStrLn $ show v
```

This is my result:

```
runtests: expected ("retval" :: [Data.Bson.Field]) in [ retval: Nothing, ok: 1.0]
```

**Comment by TonyGen** [comment]
Do: access pipe slaveOk "admin" $ runCommand1 "buildInfo"

If you type "db.version" and then "db.serverBuildInfo" without trailing parens "()", you will see what command a shell method sends to the server. Also you can see the list of commands here http://www.mongodb.org/display/DOCS/List+of+Database+Commands

Cheers,
Tony

**Comment by gregwebs** [comment]
oh, I see that you already have a serverVersion and serverBuildInfo command under Admin

**Comment by tschmorleiz** [comment]
Hi, I have a related problem. I am executing this in GHCi:

`pipe <- runIOE $ connect $ host "127.0.0.1"
 run pipe $ eval $ Javascript [] (u "db.getCollectioNames()")`

"run" is definied as:
`run pipe act = access pipe master "wiki" act`

I get 

`*** Exception: expected ("retval" :: [Data.Bson.Field]) in [ retval: ["coverage","meta","page","system.indexes"], ok: 1.0]`

Cheers, 
Thomas

**Comment by TonyGen** [comment]
Hi Thomas, try:

> run pipe allCollections
