### ISSUE TITLE
can't cabal install on OSX

### ISSUE THREAD

**Issue by dmjio** [TonyGen/mongoDB-haskell#26]
hey guys, not sure if this is an issue with me or what, but I keep getting this on cabal install mongodb

Think its an issue with the bson library.

If there's anyway I could help let me know.

https://github.com/selectel/bson-haskell/issues -- Don't see any issues here though. Maybe no osx users use bson for haskell? Maybe no haskell users use osx? :)

Data/Bson.hs:59:18:
    Could not find module `Crypto.Hash.MD5'
    There are files missing in the`cryptohash-0.7.5' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.

**Comment by unixpickle** [comment]
Worked fine for me. Maybe you have an older version of cryptohash installed?

Setup: GHC version 7.4.2, cabal-install v0.14.0 and cabal library version 1.14.0 on Mac OS 10.8.2

**Comment by dmjio** [comment]
How would I check that?

**Comment by dmjio** [comment]
I have version 0.7.5 you?

**Comment by dmjio** [comment]
My ghc is version 7.4.1, but cabal is latest

**Comment by dmjio** [comment]
Crypto/Hash/SHA1.hs:46:18:
    Could not find module `Crypto.Classes'
    There are files missing in the`crypto-api-0.10.2' package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
cryptohash-0.7.5 failed during the building phase. The exception was:
ExitFailure 1

I'm just gonna reinstall. I have yesod, snap and happstack installed. It's bound to have messed stuff up. I need virtualenv for haskell

**Comment by dmjio** [comment]
reinstall fixed it, sorry!
