### ISSUE TITLE
Read/Show instance for ObjectId

### ISSUE THREAD

**Issue by gregwebs** [TonyGen/mongoDB-haskell#3]
Web applications need to Read/Show an ObjectId when using ids in urls. The current Show instance is useful for debugging, but not quite what is needed for this. See these instances:

https://github.com/MassiveTactical/mt-mongodb/blob/master/Massive/Database/MongoDB.hs#L359

**Comment by TonyGen** [comment]
Hi Greg,

I changed the show instance of ObjectId to a continuous hex, and added a Read instance.

Thanks,
Tony

**Comment by gregwebs** [comment]
Thanks Tony!
